name = "telegram-bot"
main = "main.py"
compatibility_date = "2024-06-01"
compatibility_flags = ["python_workers"]
workers_dev = true
account_id = "215a19df1120e2c3a787071fa5a05dd9"

[vars]
TELEGRAM_TOKEN = "7746119786:AAGm0uWy-urxACu9Q9w0lP9HQ6v610K6Vcg"
CLOUDFLARE_API_TOKEN = "FfCBLP6vHcmNHRFcIAd20t1o361ps-_nNaacb_-1"
CLOUDFLARE_ACCOUNT_ID = "215a19df1120e2c3a787071fa5a05dd9"
GOOGLE_FOLDER_ID = "1SDBfV-2Zk7lriKUsgRSS6wWnyC2O7ZX0"
GOOGLE_SERVICE_ACCOUNT = "credentials.json"