name: Weekly update data.json

on:
  schedule:
    - cron: '0 6 * * 1'  # Каждый понедельник в 6:00 UTC
  workflow_dispatch:      # Возможность запускать вручную

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create credentials.json
      env:
        GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
      run: |
        echo "$GDRIVE_CREDENTIALS" | base64 -d > credentials.json

    - name: Run make_data_json.py
      run: python make_data_json.py

    - name: Commit and push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add data.json
        git commit -m "Автообновление data.json" || echo "No changes to commit"
        git push

